server:
  type: default
  rootPath: /api/

  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8080

  adminContextPath: /
  adminConnectors:
    - type: http
      port: 8081
